typography_spectrum: 0.09083547629415989
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6765942249912769
  lightness: 0.9420727789402008
  saturation: 0.5708119159098715
  rhythmicContrast: 0.7972632250748575
layout_spectrum: 0.6773798719514161
author:
  name: Seth DeSantis
  email: sthdsnts@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1def7d03-9630-4d38-a8f2-a58fc8b19969.png
name: sethryandesantis
navigation:
  - name: Resume
    id: 6448b6bd-7af2-4c65-b689-6a5a2eeb4db6
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b324dccc-0d9f-49f1-9673-12f769da669d.png
title: Live. Think. Breath. Code.
