layout_spectrum: 0.8886925980914384
typography_spectrum: 0.22244569100439548
color:
  brandColors:
    - '#2A2B2A'
    - '#EE3731'
    - '#FFFFFF'
    - '#949594'
    - '#5F605F'
  brandStrength: 0.8064214559271932
  lightness: 0.6649200364481658
  saturation: 0.6752318569924682
  rhythmicContrast: 0.339577070903033
analytics:
  google: UA-55185963-1
author:
  name: Seth DeSantis
  email: sthdsnts@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1def7d03-9630-4d38-a8f2-a58fc8b19969.png
name: sethryandesantis
navigation:
  - name: Resume
    id: 6448b6bd-7af2-4c65-b689-6a5a2eeb4db6
    type: content
  - name: Contact
    id: bec125e0-ccf4-447e-a8c4-30b45e018ae4
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b324dccc-0d9f-49f1-9673-12f769da669d.png
title: Live. Think. Code.
description: Repeat
