name: ' '
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc129ece-9595-4ecd-9257-f0ca267ae12c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9d6fc6c-2586-4ba2-935a-9ffebe50dd9a.png
layout_spectrum: 0.1368459890870433
typography_spectrum: 0.6360957083178888
analytics:
  facebook: ''
  google: UA-55185963-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2A2B2A'
    - '#EE3731'
    - '#FFFFFF'
    - '#949594'
    - '#5F605F'
  brandStrength: 0.5806992245014609
  lightness: 0.40692226768858586
  saturation: 0.6731943619620092
  rhythmicContrast: 0.9585899758816576
purpose:
  - type: contact
    label: Contact
    url: 'mailto:sthdsnts@gmail.com'
  - type: external
    label: LinkedIn
    url: 'https://www.linkedin.com/in/sethrdesantis/'
title: Seth Ryan DeSantis
description: Live. Think. Code.
author:
  name: Seth DeSantis
  url: 'http://www.sethryandesantis.com'
  email: sthdsnts@gmail.com
content_rating:
  adult: false
navigation:
  - name: Github
    id: 1ce1cd5f-e087-414b-9e0f-507dbbdf529e
    type: content
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/sethrdesantis/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/25d9b255-ae1f-4604-ab90-59eaae860af8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/25d9b255-ae1f-4604-ab90-59eaae860af8.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e79c916-12f6-4a5d-a01e-e5847669e435.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e79c916-12f6-4a5d-a01e-e5847669e435.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
