typography_spectrum: 0.6360957083178888
color:
  brandColors:
    - '#2A2B2A'
    - '#EE3731'
    - '#FFFFFF'
    - '#949594'
    - '#5F605F'
  brandStrength: 0.5806992245014609
  lightness: 0.40692226768858586
  saturation: 0.6731943619620092
  rhythmicContrast: 0.9585899758816576
layout_spectrum: 0.1368459890870433
analytics:
  google: UA-55185963-1
author:
  name: Seth DeSantis
  email: sthdsnts@gmail.com
logo: null
name: sethryandesantis
navigation:
  - name: About
    id: aa0a8b94-c73b-42cb-846f-555affc51f8f
    type: content
  - name: Github
    id: 1ce1cd5f-e087-414b-9e0f-507dbbdf529e
    type: content
  - name: Current Development
    id: fa9a4417-4bbd-4060-82ee-2c740baa8e8d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e610d5a-448f-42fe-8ab8-7b7e2afa1d24.png
title: Live. Think. Code.
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/25d9b255-ae1f-4604-ab90-59eaae860af8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/25d9b255-ae1f-4604-ab90-59eaae860af8.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: this.code( )
purpose:
  - type: contact
    url: 'mailto:sthdsnts@gmail.com'
    label: Contact
  - type: external
    url: 'https://www.linkedin.com/in/sethrdesantis/'
    label: LinkedIn
github: true
content_rating:
  adult: false
