layout_spectrum: 0.8886925980914384
typography_spectrum: 0.367393858730793
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.6637561665847898
  lightness: 0.4835619437508285
  saturation: 0.607597787398845
  rhythmicContrast: 0.9757084825541824
analytics:
  google: UA-55185963-1
author:
  name: Seth DeSantis
  email: sthdsnts@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1def7d03-9630-4d38-a8f2-a58fc8b19969.png
name: sethryandesantis
navigation:
  - name: Resume
    id: 6448b6bd-7af2-4c65-b689-6a5a2eeb4db6
    type: content
  - name: Snippets
    id: 2693ec9f-f3b0-4c6e-9430-4b602bd4489d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b324dccc-0d9f-49f1-9673-12f769da669d.png
title: Live. Think. Code.
